HomeService.EndPoint.MVC/Areas/Admin/Controllers/CommentController.cs
using HomeService.Domain.Core.HomeService.CommentEntity.AppServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HomeService.EndPoint.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CommentController : Controller
    {
        private readonly IcommentAppService _icommentAppService;

        public CommentController(IcommentAppService icommentAppService)
        {
            _icommentAppService = icommentAppService;
        }
        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var result = await _icommentAppService.GetPendings(cancellationToken);
            return View(result);
        }
        public async Task<IActionResult> GetApproved(CancellationToken cancellationToken)
        {
            var result = await _icommentAppService.GetApproved(cancellationToken);
            return View(result);
        }
        public async Task<IActionResult> GetDisApproved(CancellationToken cancellationToken)
        {
            var result = await _icommentAppService.GetDissaproved(cancellationToken);
            return View(result);
        }
        public async Task <IActionResult> Approve(int id,int ExpertId, CancellationToken cancellationToken)
        {
            await _icommentAppService.ChangeStatus(id, 1, ExpertId, cancellationToken);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DisApprove(int id,int ExpertId ,CancellationToken cancellationToken)
        {
            await _icommentAppService.ChangeStatus(id, 2, ExpertId, cancellationToken);
            return RedirectToAction("Index");
        }

    }
}

HomeService.EndPoint.MVC/Areas/Customer/Controllers/MyListingController.cs
using HomeService.Domain.Core.HomeService.CustomerEntity.AppServices;
using HomeService.Domain.Core.HomeService.CustomerEntity.DTO;
using HomeService.Domain.Core.HomeService.OfferEntity.AppServices;
using HomeService.Domain.Core.HomeService.OrderEntity.AppServices;
using HomeService.Domain.Core.HomeService.OrderEntity.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading;

namespace HomeService.EndPoint.MVC.Areas.Customer.Controllers
{
    [Authorize(Roles = "Customer")]
    [Area(areaName: "Customer")]
    public class MyListingController : Controller
    {
        private readonly IOrderAppService _orderAppService;
        private readonly IOfferAppService _offerAppService;
        private readonly ICustomerAppService _customerAppService;

        public MyListingController(IOrderAppService orderAppService, IOfferAppService offerAppService, ICustomerAppService customerAppService)
        {
            _orderAppService = orderAppService;
            _offerAppService = offerAppService;
            _customerAppService = customerAppService;
        }
        public async Task<IActionResult> Index(int Id, CancellationToken cancellationToken)
        {
            var Customer = await _customerAppService.GetById(Id, cancellationToken);
            ViewBag.Customer = Customer;
            var Orders = await _orderAppService.GetAllOfUsers(Id, cancellationToken);

            return View(Orders);
        }
        public async Task<IActionResult> GetOffers(int OrderId,int Id, CancellationToken cancellationToken)
        {
            var Customer = await _customerAppService.GetById(Id, cancellationToken);
            ViewBag.Customer = Customer;
            var Order = await _orderAppService.GetById(OrderId, cancellationToken);
            ViewBag.Order = Order;
            var Offers = await _offerAppService.GetAll(OrderId, cancellationToken);
            ViewBag.Offers = Offers;

            return View();
        }
        public async Task<IActionResult> Accept(int Id, int OrderId, CancellationToken cancellationToken)
        {
            var result = await _offerAppService.GetById(Id, cancellationToken);

            await _orderAppService.Update(result, cancellationToken);
            return LocalRedirect($"/Customer/MyListing/Index/{result.Order.CustomerId}");
        }
        public async Task<IActionResult> DeleteOffer(int Id,int CustomerId, CancellationToken cancellationToken)
        {

            await _offerAppService.Delete(Id, cancellationToken);
            return LocalRedirect($"/Customer/MyListing/Index/{CustomerId}");
        }
        [HttpPost]
        public async Task<IActionResult> Pay(int Orderid,int id, decimal amount,CancellationToken cancellationToken)
        {
            var result = await _customerAppService.Transaction(Orderid, amount, cancellationToken);
            if (result == false)
            {

                TempData["Message"] = "موجودی نا کافی";
                TempData["AlertType"] = "danger";

                return LocalRedirect($"/Customer/MyListing/Index/{id}");
            }
            await _orderAppService.ChangeStatus(Orderid, 5,cancellationToken);
            return LocalRedirect($"/Customer/MyListing/Index/{id}");
        }
    }
}

HomeService.EndPoint.MVC/Controllers/ExpertProfileController.cs
using HomeService.Domain.Core.HomeService.CommentEntity.AppServices;
using HomeService.Domain.Core.HomeService.ExpertEntity.AppServices;
using Microsoft.AspNetCore.Mvc;

namespace HomeService.EndPoint.MVC.Controllers
{
    public class ExpertProfileController : Controller
    {
        private readonly IExpertAppService _expertAppService;
        private readonly IcommentAppService _icommentAppService;

        public ExpertProfileController(IExpertAppService expertAppService, IcommentAppService icommentAppService)
        {
            _expertAppService = expertAppService;
            _icommentAppService = icommentAppService;
        }
        public async Task<IActionResult> Index(int Id, CancellationToken cancellationToken)
        {
            var result = await _expertAppService.GetById(Id, cancellationToken);
            var Comments = await _icommentAppService.GetExpertsComments(Id, cancellationToken);
            ViewBag.Comments = Comments;
            return View(result);
        }
    }
}

HomeService.EndPoint.MVC/Areas/Customer/Views/MyListing/GetOffers.cshtml
@using HomeService.Domain.Core.HomeService.OrderEntity.Enums


}@{
    var customerId = User.FindFirst("CustomerId")?.Value;
    var expertId = User.FindFirst("ExpertId")?.Value;
}

<div class="goodup-dashboard-content">
    <div class="dashboard-tlbar d-block mb-5">
        <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
                <h1 class="ft-medium fs-lg">پیشنهاد های من</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item text-muted"><a href="#">خانه</a></li>
                        <li class="breadcrumb-item text-muted"><a href="#">داشبورد</a></li>
                        <li class="breadcrumb-item"><a href="#" class="theme-cl">پیشنهاد ها</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="dashboard-widg-bar d-block">
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="dashboard-list-wraps bg-white rounded mb-4">
                    <div class="dashboard-list-wraps-head br-bottom py-3 px-3">
                        <div class="dsd-single-listing-wraps">

                            <div class="dsd-single-lst-caption">
                                <div class="dsd-single-lst-title"><h5>@ViewBag.Order.Description</h5></div>

               



                            </div>
                        </div>
                    </div>

                    <div class="dashboard-list-wraps-body py-3 px-3">
                        <div class="dashboard-listing-wraps">

                            <!-- Single Listing Item -->
                            @foreach (var x in ViewBag.Offers)
                            {
                                <div class="dsd-single-listing-wraps">

                                    <div class="dsd-single-lst-caption">
                                        <div class="dsd-single-lst-title"><h5>@x.Description</h5></div>

                                        <div class="ico-content">
                                            <div class="Goodup-ft-first">
                                                <a asp-area="" asp-controller="ExpertProfile" asp-action="Index" asp-route-Id="@x.Expert.Id">@x.Expert.FirstName @x.Expert.LastName</a>
                                                

                                            </div>
                                        </div>

                                        <div class="Goodup-price-range">
                                            @x.Price
                                            <span class="active"><i class="fas fa-dollar-sign"></i></span>
                                        </div>

                                        <div class="Goodup-ft-first">
                                            <div class="Goodup-rating">
                                                <div class="Goodup-pr-average high">@x.Expert.Rating</div>
                                                <div class="Goodup-rates">
                                                    @{

                                                        var rating = @x.Expert.Rating;
                                                        while(rating>=1)
                                                        {
                                                            <i class="fas fa-star"></i>
                                                            rating -= 1;
                                                        }
                                                    }


                                                </div>
                                            </div>

                                        </div>


                                        <div class="dsd-single-lst-footer">
                                            @if (ViewBag.Order.Expert != null)
                                            {
                                                <form asp-area="Customer" asp-controller="MyListing" asp-action="Accept" method="post">
                                                    <input type="hidden" name="Id" value="@x.Id" />
                                                    <input type="hidden" name="OrderId" value="@x.OrderId" />
                                                    <button type="submit" class="btn btn-edit mr-1" disabled>
                                                        <i class="fas fa-edit ms-1"></i> قبول کردن
                                                    </button>
                                                </form>
                                            }
                                            else
                                            {
                                                <form asp-area="Customer" asp-controller="MyListing" asp-action="Accept" method="post">
                                                    <input type="hidden" name="Id" value="@x.Id" />
                                                    <input type="hidden" name="OrderId" value="@x.OrderId" />
                                                    <button type="submit" class="btn btn-edit mr-1">
                                                        <i class="fas fa-edit ms-1"></i> قبول کردن
                                                    </button>
                                                </form>
                                            }

                                            @if (ViewBag.Order.Expert?.Id == x.Expert.Id)
                                            {
                                                <form asp-area="Customer" asp-controller="MyListing" asp-action="DeleteOffer"  method="post">
                                                    <input type="hidden" name="Id" value="@x.Id" />
                                                    <input type="hidden" name="CustomerId" value="@ViewBag.Customer.Id" />
                                                    <button type="submit" class="btn btn-delete" disabled>
                                                        <i class="fas fa-trash ms-1"></i> رد کردن
                                                    </button>
                                                </form>
                                            }
                                            else
                                            {
                                                <form asp-area="Customer" asp-controller="MyListing" asp-action="DeleteOffer" method="post">
                                                    <input type="hidden" name="Id" value="@x.Id" />                                            
                                                    <input type="hidden" name="CustomerId" value="@ViewBag.Customer.Id" />

                                                    <button type="submit" class="btn btn-delete">
                                                        <i class="fas fa-trash ms-1"></i> رد کردن
                                                    </button>
                                                </form>
                                            }
                                            @if(@ViewBag.Order.Status != StatusEnum.Done)
                                            {
                                                <form asp-area="Customer" asp-controller="Comment" asp-action="AddComments"  method="get">
												<input type="hidden" name="Id" value="@ViewBag.Customer.Id" />
												<input type="hidden" name="OfferId" value="@x.Id" />
												<button type="submit" class="btn btn-primary" disabled>
													<i class="fas fa-plus ms-1"></i> اضافه کردن کانت
												</button>
											</form>
                                            }
                                            else
                                            {
                                                <form asp-area="Customer" asp-controller="Comment" asp-action="AddComments" method="get">
                                                    <input type="hidden" name="Id" value="@ViewBag.Customer.Id" />
                                                    <input type="hidden" name="OfferId" value="@x.Id" />
                                                    <button type="submit" class="btn btn-primary">
                                                        <i class="fas fa-plus ms-1"></i> اضافه کردن کانت
                                                    </button>
                                                </form>
                                            }

                                            @if (@ViewBag.Order.Status == StatusEnum.WaitingForPayment && x.Expert.Id == @ViewBag.Order.Expert.Id)
                                            {
                                                <form asp-area="Customer" asp-controller="MyListing" asp-action="Pay" method="post">
                                                    <input type="hidden" name="id" value="@customerId" />
                                                    <input type="hidden" name="Orderid" value="@ViewBag.Order.Id" />
                                                    <input type="hidden" name="amount" value="@x.Price" />
                                                    <button type="submit" class="btn btn-warning text-dark">
                                                        <i class="fas fa-credit-card ms-1"></i> پرداخت
                                                    </button>
                                                </form>
                                            }
                                            else
                                            {
                                                <form asp-area="Customer" asp-controller="MyListing" asp-action="DeleteOffer" method="post">
                                                    <input type="hidden" name="id" value="@customerId" />
                                                    <input type="hidden" name="Orderid" value="@ViewBag.Order.Id" />
                                                    <input type="hidden" name="amount" value="@x.Price" />
                                                    <button type="submit" class="btn btn-warning text-dark" disabled>
                                                        <i class="fas fa-credit-card ms-1"></i> پرداخت
                                                    </button>
                                                </form>
                                            }





											</div>
										</div>
									</div>

								}



							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
		</div>

HomeService.EndPoint.MVC/Areas/Customer/Views/MyListing/Index.cshtml
@using Framework
@using HomeService.Domain.Core.HomeService.OrderEntity.DTO

@model List<GetOrderDTO>

@{
	var customerId = User.FindFirst("CustomerId")?.Value;
	var expertId = User.FindFirst("ExpertId")?.Value;
}



	<div class="goodup-dashboard-content">
		<div class="dashboard-tlbar d-block mb-5">
			<div class="row">
				<div class="colxl-12 col-lg-12 col-md-12">
					<h1 class="ft-medium fs-lg">آگهی های من</h1>
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item text-muted"><a href="#">خانه</a></li>
							<li class="breadcrumb-item text-muted"><a href="#">داشبورد</a></li>
							<li class="breadcrumb-item"><a href="#" class="theme-cl">آگهی های من</a></li>
						</ol>
					</nav>
				</div>
			</div>
		</div>

		<div class="dashboard-widg-bar d-block">
			<div class="row">
				<div class="col-xl-12 col-lg-12">
					<div class="dashboard-list-wraps bg-white rounded mb-4">
						<div class="dashboard-list-wraps-head br-bottom py-3 px-3">
							<div class="dashboard-list-wraps-flx">
								<h4 class="mb-0 ft-medium fs-md"><i class="fa fa-file-alt ms-2 theme-cl fs-sm"></i>آگهی های من</h4>
							</div>
						</div>

						<div class="dashboard-list-wraps-body py-3 px-3">
							<div class="dashboard-listing-wraps">

								<!-- Single Listing Item -->
								@foreach (var Order in Model)
								{
								<div class="dsd-single-listing-wraps">
									@if (Order.Images?.Count != 0)
									{
										<div class="dsd-single-lst-thumb"><img src="@Order.Images[0].ImagePath" class="img-fluid" alt="" /></div>
									}
									else
									{
										<div class="dsd-single-lst-thumb"><img src="~/Images/PlaceHolder/bg.jpg" class="img-fluid" alt="" /></div>
									}
									<div class="dsd-single-lst-caption">
										<div class="dsd-single-lst-title"><h5>@Order.Description</h5></div>
										<span class="agd-location">@Order.Status.GetEnumDisplayName()</span>
										<br>
										<span class="agd-location"><i class="lni lni-map-marker ms-1"></i>@Order.City.Titel</span>
										<div class="ico-content">
											<div class="Goodup-ft-first">
												<div class="Goodup-rating">

												</div>
												@if (@Order.Offers == null)
												{
													<div class="Goodup-price-range">
														<span class="ft-medium">هیچ پیشنهادی داده نشده</span>
													</div>
												}
												else{
													<div class="Goodup-price-range">
														<span class="ft-medium">@Order.Offers.Count پیشنهاد ثبت شده</span>
													</div>
												}

											</div>
										</div>

										<div class="dsd-single-lst-footer">

											<a asp-area="Customer" asp-controller="MyListing" asp-action="GetOffers" asp-route-Id="@customerId" asp-route-OrderId="@Order.Id" class="btn btn-view mr-1"><i class="fas fa-eye ms-1"></i>نمایش</a>

										</div>
									</div>
								</div>
								}


								

							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
		</div>