HomeService.EndPoint.MVC/Areas/Account/Controllers/LoginController.cs
using HomeService.Domain.Core.HomeService.Account.AppService;
using Microsoft.AspNetCore.Mvc;

namespace HomeService.EndPoint.MVC.Areas.Account.Controllers
{
    [Area(areaName: "Account")]
    public class LoginController : Controller
    {

        private readonly IAccountAppService _accountAppService;
        private readonly ILogger<LoginController> _logger;

        public LoginController(IAccountAppService accountAppService, ILogger<LoginController> logger)
        {

           _accountAppService = accountAppService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> login(string Email,string Password,CancellationToken cancellationToken)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");
            var succeededLogin = await _accountAppService.Login(Email, Password,cancellationToken);
            if (succeededLogin.Succeeded)
            {
                _logger.LogInformation("شخصی در تاریخ {date}لاگ این کرد", DateTime.UtcNow.ToLongDateString());
                if (User.IsInRole("Admin"))
                {

                    return LocalRedirect("/Admin/Admin/Index");
                }

                if (User.IsInRole("Expert"))
                {
                    return LocalRedirect("/Home/Index");
                }

                if (User.IsInRole("Customer"))
                    return LocalRedirect("/Home/Index");
            }

            TempData["Message"] = "ایمیل یا رمز عبور اشتباه میباشد";
            TempData["AlertType"] = "danger";

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Logout(CancellationToken cancellationToken)
        {
            await _accountAppService.Logout(cancellationToken);
            return Redirect("/home");
        }
    }
}

HomeService.EndPoint.MVC/Areas/Customer/Controllers/MyListingController.cs
using HomeService.Domain.Core.HomeService.CustomerEntity.AppServices;
using HomeService.Domain.Core.HomeService.CustomerEntity.DTO;
using HomeService.Domain.Core.HomeService.OfferEntity.AppServices;
using HomeService.Domain.Core.HomeService.OrderEntity.AppServices;
using HomeService.Domain.Core.HomeService.OrderEntity.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading;

namespace HomeService.EndPoint.MVC.Areas.Customer.Controllers
{
    [Authorize(Roles = "Customer")]
    [Area(areaName: "Customer")]
    public class MyListingController : Controller
    {
        private readonly IOrderAppService _orderAppService;
        private readonly IOfferAppService _offerAppService;
        private readonly ICustomerAppService _customerAppService;

        public MyListingController(IOrderAppService orderAppService, IOfferAppService offerAppService, ICustomerAppService customerAppService)
        {
            _orderAppService = orderAppService;
            _offerAppService = offerAppService;
            _customerAppService = customerAppService;
        }
        public async Task<IActionResult> Index(int Id, CancellationToken cancellationToken)
        {
            var Customer = await _customerAppService.GetById(Id, cancellationToken);
            ViewBag.Customer = Customer;
            var Orders = await _orderAppService.GetAllOfUsers(Id, cancellationToken);

            return View(Orders);
        }
        public async Task<IActionResult> GetOffers(int OrderId,int Id, CancellationToken cancellationToken)
        {
            var Customer = await _customerAppService.GetById(Id, cancellationToken);
            ViewBag.Customer = Customer;
            var Order = await _orderAppService.GetById(OrderId, cancellationToken);
            ViewBag.Order = Order;
            var Offers = await _offerAppService.GetAll(OrderId, cancellationToken);
            ViewBag.Offers = Offers;

            return View();
        }
        public async Task<IActionResult> Accept(int Id, int OrderId, CancellationToken cancellationToken)
        {
            var result = await _offerAppService.GetById(Id, cancellationToken);

            await _orderAppService.Update(result, cancellationToken);
            return LocalRedirect($"/Customer/MyListing/Index/{result.Order.CustomerId}");
        }
        public async Task<IActionResult> DeleteOffer(int Id,int CustomerId, CancellationToken cancellationToken)
        {

            await _offerAppService.Delete(Id, cancellationToken);
            return LocalRedirect($"/Customer/MyListing/Index/{CustomerId}");
        }
        [HttpPost]
        public async Task<IActionResult> Pay(int Orderid,int id, decimal amount,CancellationToken cancellationToken)
        {
            var result = await _customerAppService.Transaction(Orderid, amount, cancellationToken);
            if (result == false)
            {

                TempData["Message"] = "موجودی نا کافی";
                TempData["AlertType"] = "danger";

                return LocalRedirect($"/Customer/MyListing/Index/{id}");
            }
            await _orderAppService.ChangeStatus(Orderid, 5,cancellationToken);
            return LocalRedirect($"/Customer/MyListing/Index/{id}");
        }
    }
}

HomeService.EndPoint.MVC/Areas/Expert/Controllers/DashboardController.cs
using HomeService.Domain.Core.HomeService.ExpertEntity.AppServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HomeService.EndPoint.MVC.Areas.Expert.Controllers
{
    [Area("Expert")]
    [Authorize(Roles = "Expert")]
    public class DashboardController : Controller
    {
        private readonly IExpertAppService _expertAppService;

        public DashboardController(IExpertAppService expertAppService)
        {
            _expertAppService = expertAppService;
        }
        public async Task<IActionResult> Index(int Id, CancellationToken cancellationToken)
        {

            var Expert = await _expertAppService.GetById(Id, cancellationToken);
            ViewBag.Expert = Expert;
            return View();
        }
    }
}

HomeService.EndPoint.MVC/Areas/Expert/Controllers/OrdersListController.cs
using HomeService.Domain.Core.HomeService.ExpertEntity.AppServices;
using HomeService.Domain.Core.HomeService.OfferEntity.AppServices;
using HomeService.Domain.Core.HomeService.OfferEntity.DTO;
using HomeService.Domain.Core.HomeService.OrderEntity.AppServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HomeService.EndPoint.MVC.Areas.Expert.Controllers
{
    [Area(areaName: "Expert")]
    [Authorize(Roles = "Expert")]
    public class OrdersListController : Controller
    {
        private readonly IOrderAppService _orderAppService;
        private readonly IExpertAppService _expertAppService;
        private readonly IOfferAppService _offerAppService;

        public OrdersListController(IOrderAppService orderAppService, IExpertAppService expertAppService, IOfferAppService offerAppService)
        {
            _orderAppService = orderAppService;
            _expertAppService = expertAppService;
            _offerAppService = offerAppService;
        }
        public async Task<IActionResult> Index(int Id, CancellationToken cancellationToken)
        {
            var expert = await _expertAppService.GetById(Id, cancellationToken);
            ViewBag.Expert = expert;
            var result = await _expertAppService.GetOrdersForExpert(expert, cancellationToken);
            return View(result);
        }
        public async Task<IActionResult> Details(int Id, int OrderId, CancellationToken cancellationToken)
        {
            var expert = await _expertAppService.GetById(Id, cancellationToken);
            ViewBag.Expert = expert;
            var result = await _orderAppService.GetById(OrderId, cancellationToken);
            return View(result);
        }
        public async Task<IActionResult> AddOffer(int Id, int OrderId, CancellationToken cancellationToken)
        {

            var expert = await _expertAppService.GetById(Id, cancellationToken);
            ViewBag.Expert = expert;
            ViewBag.OrderId = OrderId;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Addoffer(AddOfferDTO addOfferDTO, CancellationToken cancellationToken)
        {
            try

            {
                var order = await _orderAppService.GetById(addOfferDTO.OrderId, cancellationToken);

                addOfferDTO.RequestTime = order.DateFor;
                if (order.Service.BasePrice > addOfferDTO.Price)
                {
                    TempData["Message"] = "قیمت باید بیشتر از حداقل قیمت باشد";
                    TempData["AlertType"] = "danger";
                    return LocalRedirect($"/Expert/OrdersList/AddOffer/{addOfferDTO.ExpertId}?OrderId={addOfferDTO.OrderId}");
                }

                await _offerAppService.Add(addOfferDTO, cancellationToken);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return LocalRedirect($"/Expert/OrdersList/AddOffer/{addOfferDTO.ExpertId}?OrderId={addOfferDTO.OrderId}");
            }
            return LocalRedirect($"/Expert/OrdersList/Index/{addOfferDTO.ExpertId}?OrderId={addOfferDTO.OrderId}");
        }
    }
}

HomeService.EndPoint.MVC/Areas/Account/Views/Shared/_Layout.cshtml
@{
	var customerId = User.FindFirst("CustomerId")?.Value;
	var expertId = User.FindFirst("ExpertId")?.Value;
}

<!DOCTYPE html>
<html lang="fa">

<head>
	<!-- Meta Data -->
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Goodup - قالب ثبت آگهی و دایرکتوری HTML</title>

	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.png">

	<!-- Custom CSS -->
	<link href="~/assets/css/styles.css" rel="stylesheet">
</head>

<body dir="rtl">

	<!-- Preloader -->
	<div class="preloader"></div>

	<!-- Main Wrapper -->
	<div id="main-wrapper">

		<!-- Top Header -->
		<div class="header header-light dark-text">
			<div class="container">
				<nav id="navigation" class="navigation navigation-landscape">
					<div class="nav-header">
						<a class="nav-brand" asp-controller="Home" asp-action="Index">
							<img src="~/assets/img/logo.png" class="logo" alt="" />
						</a>
						<div class="nav-toggle"></div>
						<div class="mobile_nav">
							<ul>
								<li>
									<a asp-area="Account" asp-controller="Login" asp-action="Index" class="theme-cl fs-lg">
										<i class="lni lni-user"></i>
									</a>
								</li>

							</ul>
						</div>
					</div>
					<div class="nav-menus-wrapper" style="transition-property: none;">
						<ul class="nav-menu">

							<li>
								@if (User.Identity.IsAuthenticated != true)
								{

									<a asp-area="Customer" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@customerId">پنل کاربری</a>
									<ul class="nav-dropdown nav-submenu">
										<li><a asp-area="Customer" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-dashboard ms-2"></i>داشبورد</a></li>
										<li><a asp-area="Customer" asp-controller="MyListing" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-files ms-2"></i>آگهی های من</a></li>
										<li><a asp-area="Customer" asp-controller="AddListing" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-add-files ms-2"></i>افزودن آگهی</a></li>
										<li><a asp-area="Customer" asp-controller="comment" asp-action="Index" asp-route-Id="@customerId">کامنت ها</a></li>
										<li><a asp-area="Customer" asp-controller="AddFunds" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-mastercard ms-2"></i>کیف پول</a></li>
										<li><a asp-area="Customer" asp-controller="UpdateProfile" asp-action="Index" asp-route-Id="@customerId">تنظیمات </a></li>
										<li><a asp-area="Account" asp-controller="Login" asp-action="LogOut"><i class="lni lni-power-switch ms-2"></i>خروج</a></li>

									</ul>

								}
								else if (User.IsInRole("Customer"))
								{
									<a asp-area="Customer" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@customerId">پنل کاربری</a>
									<ul class="nav-dropdown nav-submenu">
										<li><a asp-area="Customer" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-dashboard ms-2"></i>داشبورد</a></li>
										<li><a asp-area="Customer" asp-controller="MyListing" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-files ms-2"></i>آگهی های من</a></li>
										<li><a asp-area="Customer" asp-controller="AddListing" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-add-files ms-2"></i>افزودن آگهی</a></li>
										<li><a asp-area="Customer" asp-controller="comment" asp-action="Index" asp-route-Id="@customerId">کامنت ها</a></li>
										<li><a asp-area="Customer" asp-controller="AddFunds" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-mastercard ms-2"></i>کیف پول</a></li>
										<li><a asp-area="Customer" asp-controller="UpdateProfile" asp-action="Index" asp-route-Id="@customerId">تنظیمات </a></li>
										<li><a asp-area="Account" asp-controller="Login" asp-action="LogOut"><i class="lni lni-power-switch ms-2"></i>خروج</a></li>

									</ul>

								}
								else if (User.IsInRole("Expert"))
								{
									<a asp-area="Expert" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@expertId">پنل کاربری</a>
									<ul class="nav-dropdown nav-submenu">
										<li><a asp-area="Expert" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@expertId"><i class="lni lni-dashboard ms-2"></i>داشبورد</a></li>
										<li><a asp-area="Expert" asp-controller="OrdersList" asp-action="Index" asp-route-Id="@expertId"><i class="lni lni-files ms-2"></i>آگهی ها</a></li>
										<li><a asp-area="Expert" asp-controller="MyJobs" asp-action="Index" asp-route-Id="@expertId"><i class="lni lni-add-files ms-2"></i>کار های من</a></li>
										<li><a asp-area="Expert" asp-controller="UpdateProfile" asp-action="Index" asp-route-Id="@expertId">تنظیمات </a></li>
										<li><a asp-area="Account" asp-controller="Login" asp-action="LogOut"><i class="lni lni-power-switch ms-2"></i>خروج</a></li>

									</ul>

								}
								else if (User.IsInRole("Admin"))
								{
									<a asp-area="Customer" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@customerId">پنل کاربری</a>
									<ul class="nav-dropdown nav-submenu">
										<li><a asp-area="Customer" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-dashboard ms-2"></i>داشبورد</a></li>
										<li><a asp-area="Customer" asp-controller="MyListing" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-files ms-2"></i>آگهی های من</a></li>
										<li><a asp-area="Customer" asp-controller="AddListing" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-add-files ms-2"></i>افزودن آگهی</a></li>
										<li><a asp-area="Customer" asp-controller="comment" asp-action="Index" asp-route-Id="@customerId">کامنت ها</a></li>
										<li><a asp-area="Customer" asp-controller="AddFunds" asp-action="Index" asp-route-Id="@customerId"><i class="lni lni-mastercard ms-2"></i>کیف پول</a></li>
										<li><a asp-area="Customer" asp-controller="UpdateProfile" asp-action="Index" asp-route-Id="@customerId">تنظیمات </a></li>
										<li><a asp-area="Account" asp-controller="Login" asp-action="LogOut"><i class="lni lni-power-switch ms-2"></i>خروج</a></li>

									</ul>

								}
							</li>



						</ul>
						<ul class="nav-menu nav-menu-social align-to-left">
							<li>
								@if (User.Identity.IsAuthenticated != true)
								{
									<a asp-area="Account" asp-controller="Login" asp-action="Index" class="ft-bold">
										<i class="fas fa-sign-in-alt ms-1 theme-cl"></i>ورود
									</a>
								}
								else if (User.IsInRole("Customer"))
								{
									<a asp-area="Customer" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@customerId" class="theme-cl fs-lg">
										<i class="lni lni-user"></i>
									</a>
								}
								else if (User.IsInRole("Expert"))
								{
									<a asp-area="Expert" asp-controller="Dashboard" asp-action="Index" asp-route-Id="@expertId" class="theme-cl fs-lg">
										<i class="lni lni-user"></i>
									</a>
								}
								else if (User.IsInRole("Admin"))
								{
									<a asp-area="Admin" asp-controller="Admin" asp-action="Index" class="theme-cl fs-lg">
										<i class="lni lni-user"></i>
									</a>
								}
							</li>

						</ul>
					</div>
				</nav>
			</div>
		</div>
		<!-- End Navigation -->
		<div class="clearfix"></div>

		<!-- Main Content -->
		@RenderBody()


		<!-- Newsletter Section -->
		<section class="space bg-cover" style="background:#03343b url(~/assets/img/landing-bg.png) no-repeat;">
			<div class="container py-5">
				<div class="row justify-content-center">
					<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
						<div class="sec_title position-relative text-center mb-5">
							<h6 class="text-light">عضویت در خبرنامه</h6>
							<h3 class="ft-bold text-light">دریافت به روز رسانی ها و پیشنهادات پیشرفته</h3>
						</div>
					</div>
				</div>
				<div class="row align-items-center justify-content-center">
					<div class="col-xl-7 col-lg-10 col-md-12 col-sm-12 col-12">
						<form class="bg-white rounded p-1">
							<div class="row no-gutters">
								<div class="col-xl-9 col-lg-9 col-md-8 col-sm-8 col-8">
									<div class="form-group mb-0 position-relative">
										<input type="text" class="form-control b-0" placeholder="ایمیل خود را وارد کنید...">
									</div>
								</div>
								<div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 col-4">
									<div class="form-group mb-0 position-relative">
										<button class="btn full-width btn-height bg-dark text-white fs-md" type="button">عضویت</button>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</section>

		<!-- Footer -->
		<footer class="light-footer skin-light-footer style-2">
			<div class="footer-middle">
				<div class="container">
					<div class="row">
						<div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
							<div class="footer_widget">
								<img src="~/assets/img/logo.png" class="img-footer small mb-2" alt="" />
								<div class="address mt-2">
									ایران، تهران، میدان آزادی جنب مترو شادمان<br> کوچه شکوفه پلاک 8
								</div>
								<div class="address mt-3">
									09320000000<br>support@Goodup.com
								</div>
								<div class="address mt-2">
									<ul class="list-inline">
										<li class="list-inline-item"><a href="#" class="theme-cl"><i class="lni lni-facebook-filled"></i></a></li>
										<li class="list-inline-item"><a href="#" class="theme-cl"><i class="lni lni-twitter-filled"></i></a></li>
										<li class="list-inline-item"><a href="#" class="theme-cl"><i class="lni lni-youtube"></i></a></li>
										<li class="list-inline-item"><a href="#" class="theme-cl"><i class="lni lni-instagram-filled"></i></a></li>
										<li class="list-inline-item"><a href="#" class="theme-cl"><i class="lni lni-linkedin-original"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12">
							<div class="footer_widget">
								<h4 class="widget_title">راهنمای سایت</h4>
								<ul class="footer-menu">
									<li><a href="#">لیست آگهی</a></li>
									<li><a href="#">لیست آگهی دهنده</a></li>
									<li><a href="#">افزودن آگهی</a></li>
									<li><a href="#">تماس با ما</a></li>
									<li><a href="#">پیشخوان</a></li>
								</ul>
							</div>
						</div>
						<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12">
							<div class="footer_widget">
								<h4 class="widget_title">حساب کاربری</h4>
								<ul class="footer-menu">
									<li><a href="#">سایر دسته بندی</a></li>
									<li><a href="#">لینک پرداخت</a></li>
									<li><a href="#">لیست علاقه مندی</a></li>
									<li><a href="#">تنظیمات</a></li>
								</ul>
							</div>
						</div>
						<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12">
							<div class="footer_widget">
								<h4 class="widget_title">درباره شرکت</h4>
								<ul class="footer-menu">
									<li><a href="#">درباره ما</a></li>
									<li><a href="#">وظایف ما</a></li>
									<li><a href="#">کارشناسان</a></li>
									<li><a href="#">پکیج ها</a></li>
									<li><a href="#">پروفایل من</a></li>
								</ul>
							</div>
						</div>
						<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12">
							<div class="footer_widget">
								<h4 class="widget_title">لینک های مفید</h4>
								<ul class="footer-menu">
									<li><a href="#">نقشه سایت</a></li>
									<li><a href="#">حریم شخصی</a></li>
									<li><a href="#">تماس با ما</a></li>
									<li><a href="#">سوالات متداول</a></li>
									<li><a href="#">قوانین سایت</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom br-top">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-12 col-md-12 text-center">
							<p class="mb-0">© 2022 Goodup ارائه شده در سایت <a href="https://rtl-theme.com/">راست چین</a></p>
						</div>
					</div>
				</div>
			</div>
		</footer>

		<!-- Back to Top Button -->
		<a id="tops-button" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>

		<!-- Scripts -->
		<script src="~/assets/js/jquery.min.js"></script>
		<script src="~/assets/js/popper.min.js"></script>
		<script src="~/assets/js/bootstrap.min.js"></script>
		<script src="~/assets/js/slick.js"></script>
		<script src="~/assets/js/jquery.magnific-popup.min.js"></script>
		<script src="~/assets/js/dropzone.js"></script>
		<script src="~/assets/js/counterup.js"></script>
		<script src="~/assets/js/lightbox.js"></script>
		<script src="~/assets/js/moment.min.js"></script>
		<script src="~/assets/js/daterangepicker.js"></script>
		<script src="~/assets/js/jQuery.style.switcher.js"></script>
		<script src="~/assets/js/custom.js"></script>
	</div>
</body>

</html>